/**
 * Automatically generated by Zserio C++17 generator version 0.1.0 using Zserio core 2.16.0.
 * Generator setup: typeInfoCode, polymorphicAllocator.
 */

#include <zserio/HashCodeUtil.h>
#include <zserio/StringConvertUtil.h>
#include <zserio/TypeInfo.h>

#include <test_object/polymorphic_allocator/WalkerBitmask.h>

namespace test_object
{
namespace polymorphic_allocator
{

::zserio::pmr::String WalkerBitmask::toString(const ::zserio::pmr::String::allocator_type& allocator) const
{
    ::zserio::pmr::String result(allocator);
    if ((*this & WalkerBitmask::Values::ZERO) == WalkerBitmask::Values::ZERO)
    {
        result += result.empty() ? "ZERO" : " | ZERO";
    }

    return ::zserio::toString<::zserio::pmr::String::allocator_type>(
            static_cast<ZserioType::ValueType>(m_value), allocator) + "[" + result + "]";
}

} // namespace polymorphic_allocator
} // namespace test_object

namespace zserio
{
namespace detail
{

const ::zserio::pmr::ITypeInfo& TypeInfo<::test_object::polymorphic_allocator::WalkerBitmask, ::zserio::pmr::PropagatingPolymorphicAllocator<uint8_t>>::get()
{
    using AllocatorType = ::zserio::pmr::PropagatingPolymorphicAllocator<uint8_t>;

    static const ::std::array<::zserio::ItemInfo, 1> values = {
        ::zserio::ItemInfo{ "ZERO", static_cast<uint64_t>(UINT32_C(1)), false, false}
    };

    static const ::zserio::detail::BitmaskTypeInfo<AllocatorType> typeInfo = {
        "test_object.polymorphic_allocator.WalkerBitmask",
        ::zserio::typeInfo<::zserio::UInt32, ::zserio::pmr::PropagatingPolymorphicAllocator<uint8_t>>(),
        values
    };

    return typeInfo;
}

} // namespace detail
} // namespace zserio

namespace std
{

size_t hash<::test_object::polymorphic_allocator::WalkerBitmask>::operator()(const ::test_object::polymorphic_allocator::WalkerBitmask& value) const
{
    uint32_t result = ::zserio::HASH_SEED;
    result = ::zserio::calcHashCode(result,
            static_cast<::test_object::polymorphic_allocator::WalkerBitmask::ZserioType::ValueType>(value.getValue()));
    return static_cast<size_t>(result);
}

} // namespace std
