/**
 * Automatically generated by Zserio C++17 generator version 0.4.0 using Zserio core 2.16.0.
 * Generator setup: typeInfoCode, stdAllocator.
 */

#ifndef TEST_OBJECT_STD_ALLOCATOR_CREATOR_OBJECT_H
#define TEST_OBJECT_STD_ALLOCATOR_CREATOR_OBJECT_H

#include <memory>
#include <zserio/Optional.h>
#include <zserio/ITypeInfo.h>
#include <zserio/IReflectableData.h>
#include <zserio/IIntrospectableView.h>
#include <zserio/View.h>
#include <memory>
#include <zserio/ArrayView.h>
#include <zserio/BitBuffer.h>
#include <zserio/Bytes.h>
#include <zserio/String.h>
#include <zserio/Types.h>
#include <zserio/Vector.h>

#include <test_object/std_allocator/CreatorNested.h>

namespace test_object
{
namespace std_allocator
{

struct CreatorObject
{
    using allocator_type = ::std::allocator<uint8_t>;

    CreatorObject() noexcept;
    explicit CreatorObject(const allocator_type& allocator) noexcept;

    CreatorObject(CreatorObject&&) = default;
    CreatorObject(CreatorObject&& other, const allocator_type& allocator);

    CreatorObject(const CreatorObject&) = default;
    CreatorObject(const CreatorObject& other, const allocator_type& allocator);

    CreatorObject& operator=(CreatorObject&&) = default;
    CreatorObject& operator=(const CreatorObject&) = default;

    ~CreatorObject() = default;

    CreatorObject(
            ::zserio::UInt32 value_,
            ::test_object::std_allocator::CreatorNested nested_,
            ::zserio::String text_,
            ::zserio::Vector<::test_object::std_allocator::CreatorNested> nestedArray_,
            ::zserio::Vector<::zserio::String> textArray_,
            ::zserio::Optional<::zserio::Vector<::zserio::BitBuffer>> externArray_,
            ::zserio::Optional<::zserio::Vector<::zserio::Bytes>> bytesArray_,
            ::zserio::Optional<::zserio::Bool> optionalBool_,
            ::zserio::Optional<::test_object::std_allocator::CreatorNested> optionalNested_,
            const allocator_type& allocator = {});

    ::zserio::UInt32 value;
    ::test_object::std_allocator::CreatorNested nested;
    ::zserio::String text;
    ::zserio::Vector<::test_object::std_allocator::CreatorNested> nestedArray;
    ::zserio::Vector<::zserio::String> textArray;
    ::zserio::Optional<::zserio::Vector<::zserio::BitBuffer>> externArray;
    ::zserio::Optional<::zserio::Vector<::zserio::Bytes>> bytesArray;
    ::zserio::Optional<::zserio::Bool> optionalBool;
    ::zserio::Optional<::test_object::std_allocator::CreatorNested> optionalNested;
};

bool operator==(const ::test_object::std_allocator::CreatorObject& lhs, const ::test_object::std_allocator::CreatorObject& rhs);
bool operator<(const ::test_object::std_allocator::CreatorObject& lhs, const ::test_object::std_allocator::CreatorObject& rhs);
bool operator!=(const ::test_object::std_allocator::CreatorObject& lhs, const ::test_object::std_allocator::CreatorObject& rhs);
bool operator>(const ::test_object::std_allocator::CreatorObject& lhs, const ::test_object::std_allocator::CreatorObject& rhs);
bool operator<=(const ::test_object::std_allocator::CreatorObject& lhs, const ::test_object::std_allocator::CreatorObject& rhs);
bool operator>=(const ::test_object::std_allocator::CreatorObject& lhs, const ::test_object::std_allocator::CreatorObject& rhs);

} // namespace std_allocator
} // namespace test_object

namespace zserio
{

template <>
class View<::test_object::std_allocator::CreatorObject>
{
public:
    struct ZserioNestedArrayArrayTraits
    {
        using OwnerType = View<::test_object::std_allocator::CreatorObject>;

        static View<::test_object::std_allocator::CreatorNested> at(const OwnerType& owner,
                const ::test_object::std_allocator::CreatorNested& element, size_t index);

        static void read(BitStreamReader& reader, const OwnerType& owner,
                ::test_object::std_allocator::CreatorNested& element, size_t index);
    };

    explicit View(const ::test_object::std_allocator::CreatorObject& data) noexcept;

    ::zserio::UInt32 value() const;
    View<::test_object::std_allocator::CreatorNested> nested() const;
    ::std::string_view text() const;
    ArrayView<const ::test_object::std_allocator::CreatorNested, ZserioNestedArrayArrayTraits> nestedArray() const;
    ArrayView<const ::zserio::String> textArray() const;
    ::zserio::Optional<ArrayView<const ::zserio::BitBuffer>> externArray() const;
    ::zserio::Optional<ArrayView<const ::zserio::Bytes>> bytesArray() const;
    ::zserio::Optional<::zserio::Bool> optionalBool() const;
    ::zserio::Optional<View<::test_object::std_allocator::CreatorNested>> optionalNested() const;

    const ::test_object::std_allocator::CreatorObject& zserioData() const;

protected:
    View(const ::test_object::std_allocator::CreatorObject& data, const View& other) noexcept;

private:
    const ::test_object::std_allocator::CreatorObject* m_data;
};

bool operator==(const View<::test_object::std_allocator::CreatorObject>& lhs, const View<::test_object::std_allocator::CreatorObject>& rhs);
bool operator<(const View<::test_object::std_allocator::CreatorObject>& lhs, const View<::test_object::std_allocator::CreatorObject>& rhs);
bool operator!=(const View<::test_object::std_allocator::CreatorObject>& lhs, const View<::test_object::std_allocator::CreatorObject>& rhs);
bool operator>(const View<::test_object::std_allocator::CreatorObject>& lhs, const View<::test_object::std_allocator::CreatorObject>& rhs);
bool operator<=(const View<::test_object::std_allocator::CreatorObject>& lhs, const View<::test_object::std_allocator::CreatorObject>& rhs);
bool operator>=(const View<::test_object::std_allocator::CreatorObject>& lhs, const View<::test_object::std_allocator::CreatorObject>& rhs);

namespace detail
{

template <>
struct ObjectTraits<::test_object::std_allocator::CreatorObject>
{
    static void validate(const View<::test_object::std_allocator::CreatorObject>& view, ::std::string_view fieldName);

    static BitSize bitSizeOf(const View<::test_object::std_allocator::CreatorObject>& view, BitSize bitPosition);

    static void write(BitStreamWriter& writer, const View<::test_object::std_allocator::CreatorObject>& view);

    static View<::test_object::std_allocator::CreatorObject> read(BitStreamReader& reader, ::test_object::std_allocator::CreatorObject& data);
};

template <>
struct TypeInfo<::test_object::std_allocator::CreatorObject, ::std::allocator<uint8_t>>
{
    static const ::zserio::ITypeInfo& get();
};

template <>
struct Reflectable<::test_object::std_allocator::CreatorObject, ::std::allocator<uint8_t>>
{
    static ::zserio::IReflectableDataConstPtr create(const ::test_object::std_allocator::CreatorObject& value,
            const ::std::allocator<uint8_t>& allocator);

    static ::zserio::IReflectableDataPtr create(::test_object::std_allocator::CreatorObject& value,
            const ::std::allocator<uint8_t>& allocator);
};

template <>
struct Introspectable<::test_object::std_allocator::CreatorObject, ::std::allocator<uint8_t>>
{
    static ::zserio::IIntrospectableViewConstPtr create(const View<::test_object::std_allocator::CreatorObject>& view,
            const ::std::allocator<uint8_t>& allocator);
};

} // namespace detail
} // namespace zserio

namespace std
{

template <>
struct hash<::test_object::std_allocator::CreatorObject>
{
    size_t operator()(const ::test_object::std_allocator::CreatorObject& data) const;
};

template <>
struct hash<::zserio::View<::test_object::std_allocator::CreatorObject>>
{
    size_t operator()(const ::zserio::View<::test_object::std_allocator::CreatorObject>& view) const;
};

} // namespace std

#endif // TEST_OBJECT_STD_ALLOCATOR_CREATOR_OBJECT_H
