/**
 * Automatically generated by Zserio C++17 generator version 0.3.0 using Zserio core 2.16.0.
 * Generator setup: typeInfoCode, ppmrAllocator.
 */

#include <zserio/CppRuntimeException.h>
#include <zserio/HashCodeUtil.h>
#include <zserio/StringConvertUtil.h>
#include <zserio/IntrospectableView.h>
#include <zserio/ReflectableData.h>
#include <zserio/TypeInfo.h>

#include <test_object/ppmr_allocator/CreatorEnum.h>

namespace zserio
{

template <>
size_t enumToOrdinal(::test_object::ppmr_allocator::CreatorEnum value)
{
    switch (value)
    {
    case ::test_object::ppmr_allocator::CreatorEnum::ONE:
        return 0;
    case ::test_object::ppmr_allocator::CreatorEnum::TWO:
        return 1;
    case ::test_object::ppmr_allocator::CreatorEnum::MinusOne:
        return 2;
    default:
        throw ::zserio::CppRuntimeException("Unknown value for enumeration CreatorEnum: ") <<
                static_cast<typename ::std::underlying_type_t<::test_object::ppmr_allocator::CreatorEnum>>(value) << "!";
    }
}

template <>
::test_object::ppmr_allocator::CreatorEnum valueToEnum(::zserio::Int8 rawValue)
{
    switch (rawValue)
    {
    case INT8_C(0):
    case INT8_C(1):
    case INT8_C(-1):
        return static_cast<::test_object::ppmr_allocator::CreatorEnum>(static_cast<::std::underlying_type_t<::test_object::ppmr_allocator::CreatorEnum>>(rawValue));
    default:
        throw ::zserio::CppRuntimeException("Unknown value for enumeration CreatorEnum: ") << rawValue << "!";
    }
}

namespace detail
{

const ::zserio::ppmr::ITypeInfo& TypeInfo<::test_object::ppmr_allocator::CreatorEnum, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>::get()
{
    using AllocatorType = ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>;

    static const ::std::array<::zserio::ItemInfo, 3> items = {
        ::zserio::ItemInfo{ "ONE", static_cast<uint64_t>(INT8_C(0)), false, false},
        ::zserio::ItemInfo{ "TWO", static_cast<uint64_t>(INT8_C(1)), false, false},
        ::zserio::ItemInfo{ "MinusOne", static_cast<uint64_t>(INT8_C(-1)), false, false}
    };

    static const ::zserio::detail::EnumTypeInfo<AllocatorType> typeInfo = {
        "test_object.ppmr_allocator.CreatorEnum",
        ::zserio::typeInfo<::zserio::Int8, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>(),
        items
    };

    return typeInfo;
}

} // namespace detail

template <>
::zserio::ppmr::IReflectableDataPtr reflectable(::test_object::ppmr_allocator::CreatorEnum value, const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& allocator)
{
    class Reflectable : public ::zserio::detail::ReflectableDataBase<::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>
    {
    public:
        using ::zserio::detail::ReflectableDataBase<::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>::getAnyValue;

        explicit Reflectable(::test_object::ppmr_allocator::CreatorEnum value) :
                ::zserio::detail::ReflectableDataBase<::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>(
                        typeInfo<::test_object::ppmr_allocator::CreatorEnum, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>()),
                m_value(value)
        {}

        ::zserio::ppmr::Any getAnyValue(const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& alloc) const override
        {
            return ::zserio::ppmr::Any(m_value, alloc);
        }

        ::zserio::ppmr::Any getAnyValue(const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& alloc) override
        {
            return ::zserio::ppmr::Any(m_value, alloc);
        }

        ::zserio::Int8::ValueType getInt8() const override
        {
            return static_cast<typename ::std::underlying_type<::test_object::ppmr_allocator::CreatorEnum>::type>(m_value);
        }

        int64_t toInt() const override
        {
            return static_cast<typename ::std::underlying_type<::test_object::ppmr_allocator::CreatorEnum>::type>(m_value);
        }

        double toDouble() const override
        {
            return static_cast<double>(toInt());
        }

        ::zserio::ppmr::String toString(const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& alloc) const override
        {
            return ::zserio::ppmr::String(::zserio::enumToString(m_value), alloc);
        }

    private:
        ::test_object::ppmr_allocator::CreatorEnum m_value;
    };

    return std::allocate_shared<Reflectable>(allocator, value);
}

template <>
::zserio::ppmr::IIntrospectableViewConstPtr introspectable(::test_object::ppmr_allocator::CreatorEnum value, const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& allocator)
{
    class Introspectable : public ::zserio::detail::SimpleIntrospectableViewBase<::test_object::ppmr_allocator::CreatorEnum, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>
    {
    public:
        explicit Introspectable(::test_object::ppmr_allocator::CreatorEnum value) :
                ::zserio::detail::SimpleIntrospectableViewBase<::test_object::ppmr_allocator::CreatorEnum, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>(
                        typeInfo<::test_object::ppmr_allocator::CreatorEnum, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>(), value)
        {}

        ::zserio::Int8::ValueType getInt8() const override
        {
            return static_cast<typename ::std::underlying_type<::test_object::ppmr_allocator::CreatorEnum>::type>(getValue());
        }

        int64_t toInt() const override
        {
            return static_cast<typename ::std::underlying_type<::test_object::ppmr_allocator::CreatorEnum>::type>(getValue());
        }

        double toDouble() const override
        {
            return static_cast<double>(toInt());
        }

        ::zserio::ppmr::String toString(const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& alloc) const override
        {
            return ::zserio::ppmr::String(::zserio::enumToString(getValue()), alloc);
        }
    };

    return std::allocate_shared<Introspectable>(allocator, value);
}

} // namespace zserio

namespace std
{

size_t hash<::test_object::ppmr_allocator::CreatorEnum>::operator()(const ::test_object::ppmr_allocator::CreatorEnum& value) const
{
    uint32_t result = ::zserio::HASH_SEED;
    result = ::zserio::calcHashCode(result,
            static_cast<::std::underlying_type_t<::test_object::ppmr_allocator::CreatorEnum>>(::zserio::enumToValue(value)));
    return static_cast<size_t>(result);
}

} // namespace std
