/**
 * Automatically generated by Zserio C++17 generator version 0.4.0 using Zserio core 2.16.0.
 * Generator setup: typeInfoCode, ppmrAllocator.
 */

#ifndef TEST_OBJECT_PPMR_ALLOCATOR_REFLECTABLE_UTIL_OBJECT_H
#define TEST_OBJECT_PPMR_ALLOCATOR_REFLECTABLE_UTIL_OBJECT_H

#include <memory>
#include <zserio/ppmr/ITypeInfo.h>
#include <zserio/ppmr/IReflectableData.h>
#include <zserio/ppmr/IIntrospectableView.h>
#include <zserio/View.h>
#include <zserio/ppmr/PropagatingPolymorphicAllocator.h>
#include <zserio/Types.h>

#include <test_object/ppmr_allocator/ReflectableUtilChoice.h>

namespace test_object
{
namespace ppmr_allocator
{

struct ReflectableUtilObject
{
    using allocator_type = ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>;

    ReflectableUtilObject() noexcept;
    explicit ReflectableUtilObject(const allocator_type& allocator) noexcept;

    ReflectableUtilObject(ReflectableUtilObject&&) = default;
    ReflectableUtilObject(ReflectableUtilObject&& other, const allocator_type& allocator);

    ReflectableUtilObject(const ReflectableUtilObject&) = default;
    ReflectableUtilObject(const ReflectableUtilObject& other, const allocator_type& allocator);

    ReflectableUtilObject& operator=(ReflectableUtilObject&&) = default;
    ReflectableUtilObject& operator=(const ReflectableUtilObject&) = default;

    ~ReflectableUtilObject() = default;

    ReflectableUtilObject(
            ::zserio::UInt8 choiceParam_,
            ::test_object::ppmr_allocator::ReflectableUtilChoice reflectableUtilChoice_,
            const allocator_type& allocator = {});

    ::zserio::UInt8 choiceParam;
    ::test_object::ppmr_allocator::ReflectableUtilChoice reflectableUtilChoice;
};

bool operator==(const ::test_object::ppmr_allocator::ReflectableUtilObject& lhs, const ::test_object::ppmr_allocator::ReflectableUtilObject& rhs);
bool operator<(const ::test_object::ppmr_allocator::ReflectableUtilObject& lhs, const ::test_object::ppmr_allocator::ReflectableUtilObject& rhs);
bool operator!=(const ::test_object::ppmr_allocator::ReflectableUtilObject& lhs, const ::test_object::ppmr_allocator::ReflectableUtilObject& rhs);
bool operator>(const ::test_object::ppmr_allocator::ReflectableUtilObject& lhs, const ::test_object::ppmr_allocator::ReflectableUtilObject& rhs);
bool operator<=(const ::test_object::ppmr_allocator::ReflectableUtilObject& lhs, const ::test_object::ppmr_allocator::ReflectableUtilObject& rhs);
bool operator>=(const ::test_object::ppmr_allocator::ReflectableUtilObject& lhs, const ::test_object::ppmr_allocator::ReflectableUtilObject& rhs);

} // namespace ppmr_allocator
} // namespace test_object

namespace zserio
{

template <>
class View<::test_object::ppmr_allocator::ReflectableUtilObject>
{
public:
    explicit View(const ::test_object::ppmr_allocator::ReflectableUtilObject& data) noexcept;

    ::zserio::UInt8 choiceParam() const;
    View<::test_object::ppmr_allocator::ReflectableUtilChoice> reflectableUtilChoice() const;

    const ::test_object::ppmr_allocator::ReflectableUtilObject& zserioData() const;

protected:
    View(const ::test_object::ppmr_allocator::ReflectableUtilObject& data, const View& other) noexcept;

private:
    const ::test_object::ppmr_allocator::ReflectableUtilObject* m_data;
};

bool operator==(const View<::test_object::ppmr_allocator::ReflectableUtilObject>& lhs, const View<::test_object::ppmr_allocator::ReflectableUtilObject>& rhs);
bool operator<(const View<::test_object::ppmr_allocator::ReflectableUtilObject>& lhs, const View<::test_object::ppmr_allocator::ReflectableUtilObject>& rhs);
bool operator!=(const View<::test_object::ppmr_allocator::ReflectableUtilObject>& lhs, const View<::test_object::ppmr_allocator::ReflectableUtilObject>& rhs);
bool operator>(const View<::test_object::ppmr_allocator::ReflectableUtilObject>& lhs, const View<::test_object::ppmr_allocator::ReflectableUtilObject>& rhs);
bool operator<=(const View<::test_object::ppmr_allocator::ReflectableUtilObject>& lhs, const View<::test_object::ppmr_allocator::ReflectableUtilObject>& rhs);
bool operator>=(const View<::test_object::ppmr_allocator::ReflectableUtilObject>& lhs, const View<::test_object::ppmr_allocator::ReflectableUtilObject>& rhs);

namespace detail
{

template <>
struct ObjectTraits<::test_object::ppmr_allocator::ReflectableUtilObject>
{
    static void validate(const View<::test_object::ppmr_allocator::ReflectableUtilObject>& view, ::std::string_view fieldName);

    static BitSize bitSizeOf(const View<::test_object::ppmr_allocator::ReflectableUtilObject>& view, BitSize bitPosition);

    static void write(BitStreamWriter& writer, const View<::test_object::ppmr_allocator::ReflectableUtilObject>& view);

    static View<::test_object::ppmr_allocator::ReflectableUtilObject> read(BitStreamReader& reader, ::test_object::ppmr_allocator::ReflectableUtilObject& data);
};

template <>
struct TypeInfo<::test_object::ppmr_allocator::ReflectableUtilObject, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>
{
    static const ::zserio::ppmr::ITypeInfo& get();
};

template <>
struct Reflectable<::test_object::ppmr_allocator::ReflectableUtilObject, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>
{
    static ::zserio::ppmr::IReflectableDataConstPtr create(const ::test_object::ppmr_allocator::ReflectableUtilObject& value,
            const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& allocator);

    static ::zserio::ppmr::IReflectableDataPtr create(::test_object::ppmr_allocator::ReflectableUtilObject& value,
            const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& allocator);
};

template <>
struct Introspectable<::test_object::ppmr_allocator::ReflectableUtilObject, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>
{
    static ::zserio::ppmr::IIntrospectableViewConstPtr create(const View<::test_object::ppmr_allocator::ReflectableUtilObject>& view,
            const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& allocator);
};

} // namespace detail
} // namespace zserio

namespace std
{

template <>
struct hash<::test_object::ppmr_allocator::ReflectableUtilObject>
{
    size_t operator()(const ::test_object::ppmr_allocator::ReflectableUtilObject& data) const;
};

template <>
struct hash<::zserio::View<::test_object::ppmr_allocator::ReflectableUtilObject>>
{
    size_t operator()(const ::zserio::View<::test_object::ppmr_allocator::ReflectableUtilObject>& view) const;
};

} // namespace std

#endif // TEST_OBJECT_PPMR_ALLOCATOR_REFLECTABLE_UTIL_OBJECT_H
