/**
 * Automatically generated by Zserio C++17 generator version 0.4.0 using Zserio core 2.16.0.
 * Generator setup: typeInfoCode, ppmrAllocator.
 */

#include <zserio/ChoiceCaseException.h>
#include <zserio/CppRuntimeException.h>
#include <zserio/HashCodeUtil.h>
#include <zserio/IntrospectableView.h>
#include <zserio/ReflectableData.h>
#include <zserio/ReflectableUtil.h>
#include <zserio/TypeInfo.h>

#include <test_object/ppmr_allocator/ReflectableChoice.h>

namespace test_object
{
namespace ppmr_allocator
{

bool operator==(const ::test_object::ppmr_allocator::ReflectableChoice& lhs, const ::test_object::ppmr_allocator::ReflectableChoice& rhs)
{
    return static_cast<const ::test_object::ppmr_allocator::ReflectableChoice::Base&>(lhs) == static_cast<const ::test_object::ppmr_allocator::ReflectableChoice::Base&>(rhs);
}

bool operator<(const ::test_object::ppmr_allocator::ReflectableChoice& lhs, const ::test_object::ppmr_allocator::ReflectableChoice&  rhs)
{
    return static_cast<const ::test_object::ppmr_allocator::ReflectableChoice::Base&>(lhs) < static_cast<const ::test_object::ppmr_allocator::ReflectableChoice::Base&>(rhs);
}

bool operator!=(const ::test_object::ppmr_allocator::ReflectableChoice& lhs, const ::test_object::ppmr_allocator::ReflectableChoice& rhs)
{
    return !(lhs == rhs);
}

bool operator>(const ::test_object::ppmr_allocator::ReflectableChoice& lhs, const ::test_object::ppmr_allocator::ReflectableChoice& rhs)
{
    return rhs < lhs;
}

bool operator<=(const ::test_object::ppmr_allocator::ReflectableChoice& lhs, const ::test_object::ppmr_allocator::ReflectableChoice& rhs)
{
    return !(rhs < lhs);
}

bool operator>=(const ::test_object::ppmr_allocator::ReflectableChoice& lhs, const ::test_object::ppmr_allocator::ReflectableChoice& rhs)
{
    return !(lhs < rhs);
}

} // namespace ppmr_allocator
} // namespace test_object

namespace zserio
{

View<::test_object::ppmr_allocator::ReflectableChoice>::View(const ::test_object::ppmr_allocator::ReflectableChoice& data,
        ::test_object::ppmr_allocator::ReflectableEnum param_) noexcept :
        m_data(&data),
        m_param_(param_)
{}

View<::test_object::ppmr_allocator::ReflectableChoice>::View(const ::test_object::ppmr_allocator::ReflectableChoice& data,
        const View& other) noexcept :
        m_data(&data),
        m_param_(other.param())
{}

::test_object::ppmr_allocator::ReflectableEnum View<::test_object::ppmr_allocator::ReflectableChoice>::param() const
{
    return m_param_;
}

::std::string_view View<::test_object::ppmr_allocator::ReflectableChoice>::valueStr() const
{
    return ::std::string_view{get<::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr>(*m_data)};
}

::zserio::UInt32 View<::test_object::ppmr_allocator::ReflectableChoice>::value32() const
{
    return get<::test_object::ppmr_allocator::ReflectableChoice::Tag::value32>(*m_data);
}

::test_object::ppmr_allocator::ReflectableChoice::Tag View<::test_object::ppmr_allocator::ReflectableChoice>::zserioChoiceTag() const
{
    return m_data->index();
}

const ::test_object::ppmr_allocator::ReflectableChoice& View<::test_object::ppmr_allocator::ReflectableChoice>::zserioData() const
{
    return *m_data;
}

bool operator==(const View<::test_object::ppmr_allocator::ReflectableChoice>& lhs, const View<::test_object::ppmr_allocator::ReflectableChoice>& rhs)
{
    if (lhs.param() != rhs.param())
    {
        return false;
    }

    if (lhs.zserioChoiceTag() != rhs.zserioChoiceTag())
    {
        return false;
    }

    switch (lhs.zserioChoiceTag())
    {
    case ::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr:
        return (lhs.valueStr() == rhs.valueStr());
    case ::test_object::ppmr_allocator::ReflectableChoice::Tag::value32:
        return (lhs.value32() == rhs.value32());
    default:
        return true;
    }
}

bool operator<(const View<::test_object::ppmr_allocator::ReflectableChoice>& lhs, const View<::test_object::ppmr_allocator::ReflectableChoice>& rhs)
{
    if (lhs.param() != rhs.param())
    {
        return lhs.param() < rhs.param();
    }

    if (lhs.zserioChoiceTag() != rhs.zserioChoiceTag())
    {
        return lhs.zserioChoiceTag() < rhs.zserioChoiceTag();
    }

    switch (lhs.zserioChoiceTag())
    {
    case ::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr:
        return (lhs.valueStr() < rhs.valueStr());
    case ::test_object::ppmr_allocator::ReflectableChoice::Tag::value32:
        return (lhs.value32() < rhs.value32());
    default:
        return false;
    }
}

bool operator!=(const View<::test_object::ppmr_allocator::ReflectableChoice>& lhs, const View<::test_object::ppmr_allocator::ReflectableChoice>& rhs)
{
    return !(lhs == rhs);
}

bool operator>(const View<::test_object::ppmr_allocator::ReflectableChoice>& lhs, const View<::test_object::ppmr_allocator::ReflectableChoice>& rhs)
{
    return rhs < lhs;
}

bool operator<=(const View<::test_object::ppmr_allocator::ReflectableChoice>& lhs, const View<::test_object::ppmr_allocator::ReflectableChoice>& rhs)
{
    return !(rhs < lhs);
}

bool operator>=(const View<::test_object::ppmr_allocator::ReflectableChoice>& lhs, const View<::test_object::ppmr_allocator::ReflectableChoice>& rhs)
{
    return !(lhs < rhs);
}

namespace detail
{

template <>
void validate(const View<::test_object::ppmr_allocator::ReflectableChoice>& view, ::std::string_view)
{
    validate(view.param(), "'ReflectableChoice.param'");
    switch (view.param())
    {
    case ::test_object::ppmr_allocator::ReflectableEnum::VALUE1:
        // check choice case
        if (view.zserioChoiceTag() != ::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr)
        {
            throw ChoiceCaseException("Wrong case set in choice 'ReflectableChoice' (") << static_cast<size_t>(view.zserioChoiceTag()) <<
                    " != " << static_cast<size_t>(::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr) << ")!";
        }
        validate(view.valueStr(), "'ReflectableChoice.valueStr'");
        break;
    case ::test_object::ppmr_allocator::ReflectableEnum::VALUE2:
        // check choice case
        if (view.zserioChoiceTag() != ::test_object::ppmr_allocator::ReflectableChoice::Tag::value32)
        {
            throw ChoiceCaseException("Wrong case set in choice 'ReflectableChoice' (") << static_cast<size_t>(view.zserioChoiceTag()) <<
                    " != " << static_cast<size_t>(::test_object::ppmr_allocator::ReflectableChoice::Tag::value32) << ")!";
        }
        validate(view.value32(), "'ReflectableChoice.value32'");
        break;
    default:
        // empty
        if (view.zserioChoiceTag() != ::test_object::ppmr_allocator::ReflectableChoice::Tag::ZSERIO_UNDEFINED)
        {
            throw ChoiceCaseException("Wrong case set in choice 'ReflectableChoice' (should be empty)!");
        }
        break;
    }
}

template <>
BitSize bitSizeOf(const View<::test_object::ppmr_allocator::ReflectableChoice>& view, BitSize bitPosition)
{
    BitSize endBitPosition = bitPosition;
    switch (view.zserioChoiceTag())
    {
    case ::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr:
        endBitPosition += bitSizeOf(view.valueStr(), endBitPosition);
        break;
    case ::test_object::ppmr_allocator::ReflectableChoice::Tag::value32:
        endBitPosition += bitSizeOf(view.value32(), endBitPosition);
        break;
    default:
        break;
    }

    return endBitPosition - bitPosition;
}

template <>
void write(BitStreamWriter& writer, const View<::test_object::ppmr_allocator::ReflectableChoice>& view)
{
    switch (view.zserioChoiceTag())
    {
    case ::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr:
        write(writer, view.valueStr());
        break;
    case ::test_object::ppmr_allocator::ReflectableChoice::Tag::value32:
        write(writer, view.value32());
        break;
    default:
        break;
    }
}

template <>
View<::test_object::ppmr_allocator::ReflectableChoice> read(BitStreamReader& reader, ::test_object::ppmr_allocator::ReflectableChoice& data,
        ::test_object::ppmr_allocator::ReflectableEnum param_)
{
    View<::test_object::ppmr_allocator::ReflectableChoice> view(data,
            param_);
    switch (view.param())
    {
    case ::test_object::ppmr_allocator::ReflectableEnum::VALUE1:
        data.emplace<::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr>();
        read(reader, data.get<::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr>());
        break;
    case ::test_object::ppmr_allocator::ReflectableEnum::VALUE2:
        data.emplace<::test_object::ppmr_allocator::ReflectableChoice::Tag::value32>();
        read(reader, data.get<::test_object::ppmr_allocator::ReflectableChoice::Tag::value32>());
        break;
    default:
        // empty
        break;
    }

    return view;
}

const ::zserio::ppmr::ITypeInfo& TypeInfo<::test_object::ppmr_allocator::ReflectableChoice, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>::get()
{
    using AllocatorType = ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>;

    static const ::std::string_view templateName;
    static const ::zserio::Span<::zserio::BasicTemplateArgumentInfo<AllocatorType>> templateArguments;

    static const ::std::array<::zserio::BasicFieldInfo<AllocatorType>, 2> fields = {
        ::zserio::BasicFieldInfo<AllocatorType>{
            "valueStr", // schemaName
            ::zserio::typeInfo<::zserio::ppmr::String, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>(), // typeInfo
            {}, // typeArguments
            false, // isExtended
            {}, // alignment
            {}, // offset
            {}, // initializer
            false, // isOptional
            {}, // optionalClause
            {}, // constraint
            false, // isArray
            {}, // arrayLength
            false, // isPacked
            false // isImplicit
        },
        ::zserio::BasicFieldInfo<AllocatorType>{
            "value32", // schemaName
            ::zserio::typeInfo<::zserio::UInt32, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>(), // typeInfo
            {}, // typeArguments
            false, // isExtended
            {}, // alignment
            {}, // offset
            {}, // initializer
            false, // isOptional
            {}, // optionalClause
            {}, // constraint
            false, // isArray
            {}, // arrayLength
            false, // isPacked
            false // isImplicit
        }
    };

    static const ::std::array<::zserio::BasicParameterInfo<AllocatorType>, 1> parameters = {
        ::zserio::BasicParameterInfo<AllocatorType>{
            "param",
            ::zserio::typeInfo<::test_object::ppmr_allocator::ReflectableEnum, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>()
        }
    };

    static const ::zserio::Span<::zserio::BasicFunctionInfo<AllocatorType>> functions;

    static const std::array<::std::string_view, 1> case0Expressions = {
        "::test_object::ppmr_allocator::ReflectableEnum::VALUE1"
    };
    static const std::array<::std::string_view, 1> case1Expressions = {
        "::test_object::ppmr_allocator::ReflectableEnum::VALUE2"
    };
    static const ::std::array<::zserio::BasicCaseInfo<AllocatorType>, 3> cases = {
        ::zserio::BasicCaseInfo<AllocatorType>{
            case0Expressions,
            &fields[0]
        },
        ::zserio::BasicCaseInfo<AllocatorType>{
            case1Expressions,
            &fields[1]
        },
        ::zserio::BasicCaseInfo<AllocatorType>{
            {}, nullptr
        }
    };

    static const ::zserio::detail::ChoiceTypeInfo<AllocatorType> typeInfo = {
        "test_object.ppmr_allocator.ReflectableChoice",
        [](const AllocatorType& allocator) -> ::zserio::ppmr::IReflectableDataPtr
        {
            return ::std::allocate_shared<::zserio::detail::ReflectableDataOwner<::test_object::ppmr_allocator::ReflectableChoice>>(allocator);
        },
        templateName, templateArguments,
        fields, parameters, functions, "param()", cases
    };

    return typeInfo;
}

} // namespace detail

template <>
::zserio::ppmr::IReflectableDataConstPtr reflectable(const ::test_object::ppmr_allocator::ReflectableChoice& value, const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& allocator)
{
    class Reflectable : public ::zserio::detail::ReflectableDataConstAllocatorHolderBase<::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>
    {
    public:
        using ::zserio::detail::ReflectableDataConstAllocatorHolderBase<::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>::getField;
        using ::zserio::detail::ReflectableDataConstAllocatorHolderBase<::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>::getAnyValue;

        explicit Reflectable(const ::test_object::ppmr_allocator::ReflectableChoice& object, const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& alloc = {}) :
                ::zserio::detail::ReflectableDataConstAllocatorHolderBase<::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>(typeInfo<::test_object::ppmr_allocator::ReflectableChoice>(), alloc),
                m_object(object)
        {}

        ::zserio::ppmr::IReflectableDataConstPtr getField(::std::string_view name) const override
        {
            if (name == "valueStr")
            {
                return ::zserio::reflectable(
                        get<::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr>(m_object), get_allocator());
            }
            if (name == "value32")
            {
                return ::zserio::reflectable(
                        get<::test_object::ppmr_allocator::ReflectableChoice::Tag::value32>(m_object), get_allocator());
            }
            throw ::zserio::CppRuntimeException("Field '") << name << "' doesn't exist in 'ReflectableChoice'!";
        }

        ::std::string_view getChoice() const override
        {
            switch (m_object.index())
            {
            case ::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr:
                return "valueStr";
            case ::test_object::ppmr_allocator::ReflectableChoice::Tag::value32:
                return "value32";
            default:
                return "";
            }
        }

        ::zserio::ppmr::Any getAnyValue(const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& alloc) const override
        {
            return ::zserio::ppmr::Any(::std::cref(m_object), alloc);
        }

    private:
        const ::test_object::ppmr_allocator::ReflectableChoice& m_object;
    };

    return ::std::allocate_shared<Reflectable>(allocator, value);
}

template <>
::zserio::ppmr::IReflectableDataPtr reflectable(::test_object::ppmr_allocator::ReflectableChoice& value, const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& allocator)
{
    class Reflectable : public ::zserio::detail::ReflectableDataAllocatorHolderBase<::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>
    {
    public:
        using ::zserio::detail::ReflectableDataAllocatorHolderBase<::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>::getField;
        using ::zserio::detail::ReflectableDataAllocatorHolderBase<::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>::getAnyValue;

        explicit Reflectable(::test_object::ppmr_allocator::ReflectableChoice& object, const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& alloc = {}) :
                ::zserio::detail::ReflectableDataAllocatorHolderBase<::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>(typeInfo<::test_object::ppmr_allocator::ReflectableChoice>(), alloc),
                m_object(object)
        {}

        ::zserio::ppmr::IReflectableDataConstPtr getField(::std::string_view name) const override
        {
            if (name == "valueStr")
            {
                return ::zserio::reflectable(
                        get<::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr>(m_object), get_allocator());
            }
            if (name == "value32")
            {
                return ::zserio::reflectable(
                        get<::test_object::ppmr_allocator::ReflectableChoice::Tag::value32>(m_object), get_allocator());
            }
            throw ::zserio::CppRuntimeException("Field '") << name << "' doesn't exist in 'ReflectableChoice'!";
        }

        ::zserio::ppmr::IReflectableDataPtr getField(::std::string_view name) override
        {
            if (name == "valueStr")
            {
                return ::zserio::reflectable(
                        get<::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr>(m_object), get_allocator());
            }
            if (name == "value32")
            {
                return ::zserio::reflectable(
                        get<::test_object::ppmr_allocator::ReflectableChoice::Tag::value32>(m_object), get_allocator());
            }
            throw ::zserio::CppRuntimeException("Field '") << name << "' doesn't exist in 'ReflectableChoice'!";
        }

        void setField(::std::string_view name, const ::zserio::ppmr::Any& value) override
        {
            if (name == "valueStr")
            {
                m_object.emplace<::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr>(
                        ::zserio::ReflectableUtil::fromAny<::zserio::ppmr::String>(value));
                return;
            }
            if (name == "value32")
            {
                m_object.emplace<::test_object::ppmr_allocator::ReflectableChoice::Tag::value32>(
                        ::zserio::ReflectableUtil::fromAny<::zserio::UInt32>(value));
                return;
            }
            throw ::zserio::CppRuntimeException("Field '") << name << "' doesn't exist in 'ReflectableChoice'!";
        }

        ::zserio::ppmr::IReflectableDataPtr createField(::std::string_view name) override
        {
            if (name == "valueStr")
            {
                m_object.emplace<::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr>();
                return ::zserio::reflectable(get<::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr>(m_object), get_allocator());
            }
            if (name == "value32")
            {
                m_object.emplace<::test_object::ppmr_allocator::ReflectableChoice::Tag::value32>();
                return ::zserio::reflectable(get<::test_object::ppmr_allocator::ReflectableChoice::Tag::value32>(m_object), get_allocator());
            }
            throw ::zserio::CppRuntimeException("Field '") << name << "' doesn't exist in 'ReflectableChoice'!";
        }

        ::std::string_view getChoice() const override
        {
            switch (m_object.index())
            {
            case ::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr:
                return "valueStr";
            case ::test_object::ppmr_allocator::ReflectableChoice::Tag::value32:
                return "value32";
            default:
                return "";
            }
        }

        ::zserio::ppmr::Any getAnyValue(const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& alloc) const override
        {
            return ::zserio::ppmr::Any(::std::cref(m_object), alloc);
        }

        ::zserio::ppmr::Any getAnyValue(const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& alloc) override
        {
            return ::zserio::ppmr::Any(::std::ref(m_object), alloc);
        }

    private:
        ::test_object::ppmr_allocator::ReflectableChoice& m_object;
    };

    return ::std::allocate_shared<Reflectable>(allocator, value);
}

template <>
::zserio::ppmr::IIntrospectableViewConstPtr introspectable(const View<::test_object::ppmr_allocator::ReflectableChoice>& view, const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& allocator)
{
    class Introspectable : public ::zserio::detail::CompoundIntrospectableViewBase<::test_object::ppmr_allocator::ReflectableChoice, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>
    {
    public:
        explicit Introspectable(const ::zserio::View<::test_object::ppmr_allocator::ReflectableChoice>& view_, const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& alloc = {}) :
                ::zserio::detail::CompoundIntrospectableViewBase<::test_object::ppmr_allocator::ReflectableChoice, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>(
                        view_, alloc)
        {}

        ::zserio::ppmr::IIntrospectableViewConstPtr getField(::std::string_view name) const override
        {
            if (name == "valueStr")
            {
                return ::zserio::introspectable(getValue().valueStr(), get_allocator());
            }
            if (name == "value32")
            {
                return ::zserio::introspectable(getValue().value32(), get_allocator());
            }
            throw ::zserio::CppRuntimeException("Field '") << name << "' doesn't exist in 'ReflectableChoice'!";
        }

        ::zserio::ppmr::IIntrospectableViewConstPtr getParameter(::std::string_view name) const override
        {
            if (name == "param")
            {
                return ::zserio::introspectable(getValue().param(), get_allocator());
            }
            throw ::zserio::CppRuntimeException("Parameter '") << name << "' doesn't exist in 'ReflectableChoice'!";
        }

        ::std::string_view getChoice() const override
        {
            switch (getValue().zserioChoiceTag())
            {
            case ::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr:
                return "valueStr";
            case ::test_object::ppmr_allocator::ReflectableChoice::Tag::value32:
                return "value32";
            default:
                return "";
            }
        }
    };

    return ::std::allocate_shared<Introspectable>(allocator, view);
}

} // namespace zserio

namespace std
{

size_t hash<::test_object::ppmr_allocator::ReflectableChoice>::operator()(const ::test_object::ppmr_allocator::ReflectableChoice& value) const
{
    uint32_t result = ::zserio::HASH_SEED;
    result = ::zserio::calcHashCode(result, static_cast<const ::test_object::ppmr_allocator::ReflectableChoice::Base&>(value));
    return static_cast<size_t>(result);
}

size_t hash<::zserio::View<::test_object::ppmr_allocator::ReflectableChoice>>::operator()(const ::zserio::View<::test_object::ppmr_allocator::ReflectableChoice>& view) const
{
    uint32_t result = ::zserio::HASH_SEED;
    result = ::zserio::calcHashCode(result, view.param());
    switch (view.zserioChoiceTag())
    {
    case ::test_object::ppmr_allocator::ReflectableChoice::Tag::valueStr:
        result = ::zserio::calcHashCode(result, view.valueStr());
        break;
    case ::test_object::ppmr_allocator::ReflectableChoice::Tag::value32:
        result = ::zserio::calcHashCode(result, view.value32());
        break;
    default:
        break;
    }

    return static_cast<size_t>(result);
}

} // namespace std
