/**
 * Automatically generated by Zserio C++17 generator version 0.3.0 using Zserio core 2.16.0.
 * Generator setup: typeInfoCode, ppmrAllocator.
 */

#ifndef TEST_OBJECT_PPMR_ALLOCATOR_WALKER_OBJECT_H
#define TEST_OBJECT_PPMR_ALLOCATOR_WALKER_OBJECT_H

#include <memory>
#include <zserio/ppmr/Optional.h>
#include <zserio/ppmr/ITypeInfo.h>
#include <zserio/ppmr/IReflectableData.h>
#include <zserio/ppmr/IIntrospectableView.h>
#include <zserio/View.h>
#include <zserio/ppmr/PropagatingPolymorphicAllocator.h>
#include <zserio/ArrayView.h>
#include <zserio/Types.h>
#include <zserio/ppmr/String.h>
#include <zserio/ppmr/Vector.h>

#include <test_object/ppmr_allocator/WalkerChoice.h>
#include <test_object/ppmr_allocator/WalkerNested.h>
#include <test_object/ppmr_allocator/WalkerUnion.h>

namespace test_object
{
namespace ppmr_allocator
{

struct WalkerObject
{
    using allocator_type = ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>;

    WalkerObject() noexcept;
    explicit WalkerObject(const allocator_type& allocator) noexcept;

    WalkerObject(WalkerObject&&) = default;
    WalkerObject(WalkerObject&& other, const allocator_type& allocator);

    WalkerObject(const WalkerObject&) = default;
    WalkerObject(const WalkerObject& other, const allocator_type& allocator);

    WalkerObject& operator=(WalkerObject&&) = default;
    WalkerObject& operator=(const WalkerObject&) = default;

    ~WalkerObject() = default;

    WalkerObject(
            ::zserio::UInt32 identifier_,
            ::zserio::ppmr::Optional<::test_object::ppmr_allocator::WalkerNested> nested_,
            ::zserio::ppmr::String text_,
            ::zserio::ppmr::Vector<::test_object::ppmr_allocator::WalkerUnion> unionArray_,
            ::zserio::ppmr::Optional<::zserio::ppmr::Vector<::test_object::ppmr_allocator::WalkerUnion>> optionalUnionArray_,
            ::zserio::UInt8 choiceSelector_,
            ::test_object::ppmr_allocator::WalkerChoice choiceField_,
            const allocator_type& allocator = {});

    ::zserio::UInt32 identifier;
    ::zserio::ppmr::Optional<::test_object::ppmr_allocator::WalkerNested> nested;
    ::zserio::ppmr::String text;
    ::zserio::ppmr::Vector<::test_object::ppmr_allocator::WalkerUnion> unionArray;
    ::zserio::ppmr::Optional<::zserio::ppmr::Vector<::test_object::ppmr_allocator::WalkerUnion>> optionalUnionArray;
    ::zserio::UInt8 choiceSelector;
    ::test_object::ppmr_allocator::WalkerChoice choiceField;
};

bool operator==(const ::test_object::ppmr_allocator::WalkerObject& lhs, const ::test_object::ppmr_allocator::WalkerObject& rhs);
bool operator<(const ::test_object::ppmr_allocator::WalkerObject& lhs, const ::test_object::ppmr_allocator::WalkerObject& rhs);
bool operator!=(const ::test_object::ppmr_allocator::WalkerObject& lhs, const ::test_object::ppmr_allocator::WalkerObject& rhs);
bool operator>(const ::test_object::ppmr_allocator::WalkerObject& lhs, const ::test_object::ppmr_allocator::WalkerObject& rhs);
bool operator<=(const ::test_object::ppmr_allocator::WalkerObject& lhs, const ::test_object::ppmr_allocator::WalkerObject& rhs);
bool operator>=(const ::test_object::ppmr_allocator::WalkerObject& lhs, const ::test_object::ppmr_allocator::WalkerObject& rhs);

} // namespace ppmr_allocator
} // namespace test_object

namespace zserio
{

template <>
class View<::test_object::ppmr_allocator::WalkerObject>
{
public:
    explicit View(const ::test_object::ppmr_allocator::WalkerObject& data) noexcept;

    ::zserio::UInt32 identifier() const;
    ::zserio::ppmr::Optional<View<::test_object::ppmr_allocator::WalkerNested>> nested() const;
    ::std::string_view text() const;
    ArrayView<const ::test_object::ppmr_allocator::WalkerUnion> unionArray() const;
    ::zserio::ppmr::Optional<ArrayView<const ::test_object::ppmr_allocator::WalkerUnion>> optionalUnionArray() const;
    ::zserio::UInt8 choiceSelector() const;
    View<::test_object::ppmr_allocator::WalkerChoice> choiceField() const;

    const ::test_object::ppmr_allocator::WalkerObject& zserioData() const;

protected:
    View(const ::test_object::ppmr_allocator::WalkerObject& data, const View& other) noexcept;

private:
    const ::test_object::ppmr_allocator::WalkerObject* m_data;
};

bool operator==(const View<::test_object::ppmr_allocator::WalkerObject>& lhs, const View<::test_object::ppmr_allocator::WalkerObject>& rhs);
bool operator<(const View<::test_object::ppmr_allocator::WalkerObject>& lhs, const View<::test_object::ppmr_allocator::WalkerObject>& rhs);
bool operator!=(const View<::test_object::ppmr_allocator::WalkerObject>& lhs, const View<::test_object::ppmr_allocator::WalkerObject>& rhs);
bool operator>(const View<::test_object::ppmr_allocator::WalkerObject>& lhs, const View<::test_object::ppmr_allocator::WalkerObject>& rhs);
bool operator<=(const View<::test_object::ppmr_allocator::WalkerObject>& lhs, const View<::test_object::ppmr_allocator::WalkerObject>& rhs);
bool operator>=(const View<::test_object::ppmr_allocator::WalkerObject>& lhs, const View<::test_object::ppmr_allocator::WalkerObject>& rhs);

namespace detail
{

template <>
void validate(const View<::test_object::ppmr_allocator::WalkerObject>& view, ::std::string_view fieldName);

template <>
BitSize bitSizeOf(const View<::test_object::ppmr_allocator::WalkerObject>& view, BitSize bitPosition);

template <>
void write(BitStreamWriter& writer, const View<::test_object::ppmr_allocator::WalkerObject>& view);

template <>
View<::test_object::ppmr_allocator::WalkerObject> read(BitStreamReader& reader, ::test_object::ppmr_allocator::WalkerObject& data);

template <>
struct TypeInfo<::test_object::ppmr_allocator::WalkerObject, ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>>
{
    static const ::zserio::ppmr::ITypeInfo& get();
};

} // namespace detail

template <>
::zserio::ppmr::IReflectableDataConstPtr reflectable(const ::test_object::ppmr_allocator::WalkerObject& value, const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& allocator);

template <>
::zserio::ppmr::IReflectableDataPtr reflectable(::test_object::ppmr_allocator::WalkerObject& value, const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& allocator);

template <>
::zserio::ppmr::IIntrospectableViewConstPtr introspectable(const View<::test_object::ppmr_allocator::WalkerObject>& view, const ::zserio::ppmr::PropagatingPolymorphicAllocator<uint8_t>& allocator);

} // namespace zserio

namespace std
{

template <>
struct hash<::test_object::ppmr_allocator::WalkerObject>
{
    size_t operator()(const ::test_object::ppmr_allocator::WalkerObject& data) const;
};

template <>
struct hash<::zserio::View<::test_object::ppmr_allocator::WalkerObject>>
{
    size_t operator()(const ::zserio::View<::test_object::ppmr_allocator::WalkerObject>& view) const;
};

} // namespace std

#endif // TEST_OBJECT_PPMR_ALLOCATOR_WALKER_OBJECT_H
