/**
 * Automatically generated by Zserio C++17 generator version 0.3.0 using Zserio core 2.16.0.
 * Generator setup: typeInfoCode, pmrAllocator.
 */

#ifndef TEST_OBJECT_PMR_ALLOCATOR_DEBUG_STRING_PARAM_OBJECT_H
#define TEST_OBJECT_PMR_ALLOCATOR_DEBUG_STRING_PARAM_OBJECT_H

#include <memory>
#include <zserio/pmr/ITypeInfo.h>
#include <zserio/pmr/IReflectableData.h>
#include <zserio/pmr/IIntrospectableView.h>
#include <zserio/View.h>
#include <memory_resource>
#include <zserio/Types.h>
#include <zserio/pmr/String.h>

namespace test_object
{
namespace pmr_allocator
{

struct DebugStringParamObject
{
    using allocator_type = ::std::pmr::polymorphic_allocator<uint8_t>;

    DebugStringParamObject() noexcept;
    explicit DebugStringParamObject(const allocator_type& allocator) noexcept;

    DebugStringParamObject(DebugStringParamObject&&) = default;
    DebugStringParamObject(DebugStringParamObject&& other, const allocator_type& allocator);

    DebugStringParamObject(const DebugStringParamObject&) = default;
    DebugStringParamObject(const DebugStringParamObject& other, const allocator_type& allocator);

    DebugStringParamObject& operator=(DebugStringParamObject&&) = default;
    DebugStringParamObject& operator=(const DebugStringParamObject&) = default;

    ~DebugStringParamObject() = default;

    explicit DebugStringParamObject(
            ::zserio::pmr::String text_,
            const allocator_type& allocator = {});

    ::zserio::pmr::String text;
};

bool operator==(const ::test_object::pmr_allocator::DebugStringParamObject& lhs, const ::test_object::pmr_allocator::DebugStringParamObject& rhs);
bool operator<(const ::test_object::pmr_allocator::DebugStringParamObject& lhs, const ::test_object::pmr_allocator::DebugStringParamObject& rhs);
bool operator!=(const ::test_object::pmr_allocator::DebugStringParamObject& lhs, const ::test_object::pmr_allocator::DebugStringParamObject& rhs);
bool operator>(const ::test_object::pmr_allocator::DebugStringParamObject& lhs, const ::test_object::pmr_allocator::DebugStringParamObject& rhs);
bool operator<=(const ::test_object::pmr_allocator::DebugStringParamObject& lhs, const ::test_object::pmr_allocator::DebugStringParamObject& rhs);
bool operator>=(const ::test_object::pmr_allocator::DebugStringParamObject& lhs, const ::test_object::pmr_allocator::DebugStringParamObject& rhs);

} // namespace pmr_allocator
} // namespace test_object

namespace zserio
{

template <>
class View<::test_object::pmr_allocator::DebugStringParamObject>
{
public:
    explicit View(const ::test_object::pmr_allocator::DebugStringParamObject& data,
            ::zserio::Int32 param_) noexcept;

    ::zserio::Int32 param() const;

    ::std::string_view text() const;

    const ::test_object::pmr_allocator::DebugStringParamObject& zserioData() const;

protected:
    View(const ::test_object::pmr_allocator::DebugStringParamObject& data, const View& other) noexcept;

private:
    const ::test_object::pmr_allocator::DebugStringParamObject* m_data;
    ::zserio::Int32 m_param_;
};

bool operator==(const View<::test_object::pmr_allocator::DebugStringParamObject>& lhs, const View<::test_object::pmr_allocator::DebugStringParamObject>& rhs);
bool operator<(const View<::test_object::pmr_allocator::DebugStringParamObject>& lhs, const View<::test_object::pmr_allocator::DebugStringParamObject>& rhs);
bool operator!=(const View<::test_object::pmr_allocator::DebugStringParamObject>& lhs, const View<::test_object::pmr_allocator::DebugStringParamObject>& rhs);
bool operator>(const View<::test_object::pmr_allocator::DebugStringParamObject>& lhs, const View<::test_object::pmr_allocator::DebugStringParamObject>& rhs);
bool operator<=(const View<::test_object::pmr_allocator::DebugStringParamObject>& lhs, const View<::test_object::pmr_allocator::DebugStringParamObject>& rhs);
bool operator>=(const View<::test_object::pmr_allocator::DebugStringParamObject>& lhs, const View<::test_object::pmr_allocator::DebugStringParamObject>& rhs);

namespace detail
{

template <>
void validate(const View<::test_object::pmr_allocator::DebugStringParamObject>& view, ::std::string_view fieldName);

template <>
BitSize bitSizeOf(const View<::test_object::pmr_allocator::DebugStringParamObject>& view, BitSize bitPosition);

template <>
void write(BitStreamWriter& writer, const View<::test_object::pmr_allocator::DebugStringParamObject>& view);

template <>
View<::test_object::pmr_allocator::DebugStringParamObject> read(BitStreamReader& reader, ::test_object::pmr_allocator::DebugStringParamObject& data,
        ::zserio::Int32 param_);

template <>
struct TypeInfo<::test_object::pmr_allocator::DebugStringParamObject, ::std::pmr::polymorphic_allocator<uint8_t>>
{
    static const ::zserio::pmr::ITypeInfo& get();
};

} // namespace detail

template <>
::zserio::pmr::IReflectableDataConstPtr reflectable(const ::test_object::pmr_allocator::DebugStringParamObject& value, const ::std::pmr::polymorphic_allocator<uint8_t>& allocator);

template <>
::zserio::pmr::IReflectableDataPtr reflectable(::test_object::pmr_allocator::DebugStringParamObject& value, const ::std::pmr::polymorphic_allocator<uint8_t>& allocator);

template <>
::zserio::pmr::IIntrospectableViewConstPtr introspectable(const View<::test_object::pmr_allocator::DebugStringParamObject>& view, const ::std::pmr::polymorphic_allocator<uint8_t>& allocator);

} // namespace zserio

namespace std
{

template <>
struct hash<::test_object::pmr_allocator::DebugStringParamObject>
{
    size_t operator()(const ::test_object::pmr_allocator::DebugStringParamObject& data) const;
};

template <>
struct hash<::zserio::View<::test_object::pmr_allocator::DebugStringParamObject>>
{
    size_t operator()(const ::zserio::View<::test_object::pmr_allocator::DebugStringParamObject>& view) const;
};

} // namespace std

#endif // TEST_OBJECT_PMR_ALLOCATOR_DEBUG_STRING_PARAM_OBJECT_H
