/**
 * Automatically generated by Zserio C++17 generator version 0.4.0 using Zserio core 2.16.1.
 * Generator setup: typeInfoCode, pmrAllocator.
 */

#ifndef TEST_OBJECT_PMR_ALLOCATOR_REFLECTABLE_CHOICE_H
#define TEST_OBJECT_PMR_ALLOCATOR_REFLECTABLE_CHOICE_H

#include <memory>

#include <zserio/pmr/Variant.h>
#include <zserio/ChoiceTag.h>
#include <zserio/pmr/ITypeInfo.h>
#include <zserio/pmr/IReflectableData.h>
#include <zserio/pmr/IIntrospectableView.h>
#include <zserio/View.h>
#include <zserio/Types.h>
#include <zserio/pmr/String.h>

#include <test_object/pmr_allocator/ReflectableEnum.h>

namespace test_object
{
namespace pmr_allocator
{

// forward declaration
struct ReflectableChoice;

} // namespace pmr_allocator
} // namespace test_object

namespace zserio
{
namespace detail
{

template <>
struct ChoiceTag<::test_object::pmr_allocator::ReflectableChoice>
{
    enum Tag : size_t
    {
        ZSERIO_UNDEFINED,
        valueStr,
        value32
    };
};

} // namespace detail
} // namespace zserio

namespace test_object
{
namespace pmr_allocator
{

struct ReflectableChoice : ::zserio::pmr::Variant<::zserio::detail::ChoiceTag<ReflectableChoice>::Tag,
        ::std::monostate,
        ::zserio::pmr::String,
        ::zserio::UInt32>
{
    using Tag = ::zserio::detail::ChoiceTag<ReflectableChoice>::Tag;
    using Base = ::zserio::pmr::Variant<Tag,
            ::std::monostate,
            ::zserio::pmr::String,
            ::zserio::UInt32>;
    using Base::Base;
};

bool operator==(const ::test_object::pmr_allocator::ReflectableChoice& lhs, const ::test_object::pmr_allocator::ReflectableChoice& rhs);
bool operator<(const ::test_object::pmr_allocator::ReflectableChoice& lhs, const ::test_object::pmr_allocator::ReflectableChoice& rhs);
bool operator!=(const ::test_object::pmr_allocator::ReflectableChoice& lhs, const ::test_object::pmr_allocator::ReflectableChoice& rhs);
bool operator>(const ::test_object::pmr_allocator::ReflectableChoice& lhs, const ::test_object::pmr_allocator::ReflectableChoice& rhs);
bool operator<=(const ::test_object::pmr_allocator::ReflectableChoice& lhs, const ::test_object::pmr_allocator::ReflectableChoice& rhs);
bool operator>=(const ::test_object::pmr_allocator::ReflectableChoice& lhs, const ::test_object::pmr_allocator::ReflectableChoice& rhs);

} // namespace pmr_allocator
} // namespace test_object

namespace zserio
{

template <>
class View<::test_object::pmr_allocator::ReflectableChoice>
{
public:
    explicit View(const ::test_object::pmr_allocator::ReflectableChoice& data,
            ::test_object::pmr_allocator::ReflectableEnum param_) noexcept;

    ::test_object::pmr_allocator::ReflectableEnum param() const;

    ::std::string_view valueStr() const;
    ::zserio::UInt32 value32() const;

    ::test_object::pmr_allocator::ReflectableChoice::Tag zserioChoiceTag() const;
    const ::test_object::pmr_allocator::ReflectableChoice& zserioData() const;

protected:
    View(const ::test_object::pmr_allocator::ReflectableChoice& data, const View& other) noexcept;

private:
    const ::test_object::pmr_allocator::ReflectableChoice* m_data;
    ::test_object::pmr_allocator::ReflectableEnum m_param_;
};

bool operator==(const View<::test_object::pmr_allocator::ReflectableChoice>& lhs, const View<::test_object::pmr_allocator::ReflectableChoice>& rhs);
bool operator<(const View<::test_object::pmr_allocator::ReflectableChoice>& lhs, const View<::test_object::pmr_allocator::ReflectableChoice>& rhs);
bool operator!=(const View<::test_object::pmr_allocator::ReflectableChoice>& lhs, const View<::test_object::pmr_allocator::ReflectableChoice>& rhs);
bool operator>(const View<::test_object::pmr_allocator::ReflectableChoice>& lhs, const View<::test_object::pmr_allocator::ReflectableChoice>& rhs);
bool operator<=(const View<::test_object::pmr_allocator::ReflectableChoice>& lhs, const View<::test_object::pmr_allocator::ReflectableChoice>& rhs);
bool operator>=(const View<::test_object::pmr_allocator::ReflectableChoice>& lhs, const View<::test_object::pmr_allocator::ReflectableChoice>& rhs);

namespace detail
{

template <>
struct ObjectTraits<::test_object::pmr_allocator::ReflectableChoice>
{
    using Parameters = std::tuple<
            ::test_object::pmr_allocator::ReflectableEnum>;

    static void validate(const View<::test_object::pmr_allocator::ReflectableChoice>& view, ::std::string_view fieldName);

    static BitSize bitSizeOf(const View<::test_object::pmr_allocator::ReflectableChoice>& view, BitSize bitPosition);

    static void write(BitStreamWriter& writer, const View<::test_object::pmr_allocator::ReflectableChoice>& view);

    static View<::test_object::pmr_allocator::ReflectableChoice> read(BitStreamReader& reader, ::test_object::pmr_allocator::ReflectableChoice& data,
            ::test_object::pmr_allocator::ReflectableEnum param_);
};

template <>
struct TypeInfo<::test_object::pmr_allocator::ReflectableChoice, ::std::pmr::polymorphic_allocator<uint8_t>>
{
    static const ::zserio::pmr::ITypeInfo& get();
};

template <>
struct Reflectable<::test_object::pmr_allocator::ReflectableChoice, ::std::pmr::polymorphic_allocator<uint8_t>>
{
    static ::zserio::pmr::IReflectableDataConstPtr create(
            const ::test_object::pmr_allocator::ReflectableChoice& value, const ::std::pmr::polymorphic_allocator<uint8_t>& allocator);

    static ::zserio::pmr::IReflectableDataPtr create(
            ::test_object::pmr_allocator::ReflectableChoice& value, const ::std::pmr::polymorphic_allocator<uint8_t>& allocator);
};

template <>
struct Introspectable<::test_object::pmr_allocator::ReflectableChoice, ::std::pmr::polymorphic_allocator<uint8_t>>
{
    static ::zserio::pmr::IIntrospectableViewConstPtr create(
            const View<::test_object::pmr_allocator::ReflectableChoice>& view, const ::std::pmr::polymorphic_allocator<uint8_t>& allocator);
};

} // namespace detail
} // namespace zserio

namespace std
{

template <>
struct hash<::test_object::pmr_allocator::ReflectableChoice>
{
    size_t operator()(const ::test_object::pmr_allocator::ReflectableChoice& value) const;
};

template <>
struct hash<::zserio::View<::test_object::pmr_allocator::ReflectableChoice>>
{
    size_t operator()(const ::zserio::View<::test_object::pmr_allocator::ReflectableChoice>& view) const;
};

} // namespace std

#endif // TEST_OBJECT_PMR_ALLOCATOR_REFLECTABLE_CHOICE_H
