name: Linux extension

on:
  workflow_call:

jobs:
  extension:
    strategy:
      fail-fast: false
      matrix:
        include:
        - { os: "ubuntu-22.04", java-version: 8 }
        - { os: "ubuntu-22.04", java-version: 11 }
        - { os: "ubuntu-24.04", java-version: 17 }

    runs-on: ${{matrix.os}}
    name: ${{matrix.os}}-java${{matrix.java-version}}

    steps:
    - name: "Set up environment"
      run: |
        if [[ "${{matrix.os}}" == "ubuntu-24.04" ]] ; then
            echo "CLANG_FORMAT_BIN=clang-format-18" >> ${GITHUB_ENV}
        fi
        echo "SPOTBUGS_HOME=${RUNNER_WORKSPACE}/spotbugs-4.8.2" >> ${GITHUB_ENV}

    - name: Apt update # with workaround for 'Unable to connect to ppa.launchpad.net' failure
      run: sudo apt-get update --option Acquire::Retries=100 --option Acquire::http::Timeout="300"

    - name: Set up Java ${{matrix.java-version}}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{matrix.java-version}}

    - name: Install clang-format-18 tool
      if: ${{ env.CLANG_FORMAT_BIN != '' }}
      run: |
        sudo apt-get install clang-format-18

    - name: Install specific version of Java static code analysis tool (spotbugs)
      run: |
        wget https://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs/4.8.2/spotbugs-4.8.2.zip \
            -P "${RUNNER_WORKSPACE}"
        unzip "${RUNNER_WORKSPACE}"/spotbugs-4.8.2.zip -d "${RUNNER_WORKSPACE}"

    - name: "Checkout"
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build Zserio C++17 extension and Zserio bundle
      run: |
        mkdir -p "${RUNNER_WORKSPACE}/build/download"
        pushd "${RUNNER_WORKSPACE}/build/download"
        ARTIFACT_ID="3537314864"
        curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -L -o linux-release-2.16.1.zip "https://api.github.com/repos/ndsev/zserio/actions/artifacts/${ARTIFACT_ID}/zip"
        unzip linux-release-2.16.1.zip
        unzip zserio-2.16.1-bin.zip
        popd
        scripts/build.sh cpp zserio -z "${RUNNER_WORKSPACE}/build/download"

    - name: Upload Zserio C++17 extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: "zserio-cpp17-java${{matrix.java-version}}"
        path: distr/zserio_cpp17*.jar

    - name: Upload Zserio bundle with C++17 extension
      uses: actions/upload-artifact@v4
      with:
        name: "zserio-java${{matrix.java-version}}"
        path: |
          distr/zserio.jar
          distr/zserio_javadocs.jar
          distr/zserio_sources.jar
